Controller Class Reference
The class-object used to interface between the serial interface and the stepper motor drivers.
#include <Controller.h>
Classes
struct arm_command
The structure used to define the overall instruction parsed from serial input.
Public Types
enum Arm_Operation {
ROTATE,
GRAB,
EXTEND,
MICROSTEPS,
ERROR
 }
Used to define common commands parsed by the arm.
enum microsteps {
HALF,
QUARTER,
EIGTH,
SIXTEENTH,
THIRTY_SECOND
 }
typedef enum Controller::microsteps Microsteps
Used to placehold common Microstep configs for the motor drivers.
typedef struct Controller::arm_command Arm_Command
Type for the Arm_Command Struct to allow easy definition.
Public Member Functions
Controller ()
Constructor for the controller object In this constructor, the motors are created on the heap, and then the motor pointer vars now point to the motors on the heap. currentCmd is not initialized, because it does not need to be pointed to at the minute.
virtual ~Controller ()
Destructor for the controller object Has no purpose, therefore does nothing.
void parseSerial (String rawinput)
Translates Serial or Other Input into an Arm_Command struct object This function will take the string input, and then parse based on the first character of the string. Parsing goes as follows: -Any commands related to rotation will start with an 'r' or 'R', then followed by a double indicating revolutions -Any commands related to gripping will start with a 'g' or 'G', then followed by a 0 or 1. Other values will trigger an exception -Any commands related to extending the arm will start with an 'e' or 'E', then followed by a double indicating motor rotation. We will assert that the value is between -1 and 1 for now -Any unrecognized letter will return the ERROR enum and 1 as the value. Serial should display an error message, or trigger an exception Once the command is selected, the remaining value is parsed as a double, and then pointed to in the Arm_Command Pointer.
void printExec ()
Debug Function to test the parser Prints output in the serial connection based on the values in currentCmd.
void executeCmd ()
Runs Commands based on data pointed to by currentCmd Uses the parsing rules defined by parseSerial and then do the respective action.
Arm_Command * getCommand ()
Getter method for the currentCmd pointer.
void setCommand (Arm_Command *cmd)
Setter method for the currentCmd pointer.
Detailed Description
The class-object used to interface between the serial interface and the stepper motor drivers.
Definition at line 20 of file Controller.h.
Member Typedef Documentation
Arm_Command
Controller::Arm_Command
Type for the Arm_Command Struct to allow easy definition.
See also
Controller::arm_command
Member Enumeration Documentation
Arm_Operation
enum Controller::Arm_Operation
Used to define common commands parsed by the arm.
Enumerator
ROTATE Run the Wrist Rotation Motor
GRAB Run the Grab motor
EXTEND Run the Arm Extender Motor
MICROSTEPS Change the Microsteps for the driver
ERROR Default Error Placeholder
Definition at line 27 of file Controller.h.
microsteps
enum Controller::microsteps
Enumerator
HALF 1/2 Microstep Ratio
QUARTER 1/4 Microstep Ratio
EIGTH 1/8 Microstep Ratio
SIXTEENTH 1/16 Microstep Ratio
THIRTY_SECOND 1/32 Microstep Ratio
Definition at line 38 of file Controller.h.
Member Function Documentation
executeCmd()
Controller::executeCmd ()
Runs Commands based on data pointed to by currentCmd Uses the parsing rules defined by parseSerial and then do the respective action.
See also
Controller::parseSerial
Definition at line 111 of file Controller.cpp.
References getCommand(), Controller::arm_command::op, and Controller::arm_command::value.
getCommand()
Controller::getCommand ()
Getter method for the currentCmd pointer.
Returns
Pointer to the Arm_Command object of the pointer
Definition at line 40 of file Controller.cpp.
Referenced by executeCmd(), and printExec().
parseSerial()
Controller::parseSerial (String rawinput)
Translates Serial or Other Input into an Arm_Command struct object This function will take the string input, and then parse based on the first character of the string. Parsing goes as follows: -Any commands related to rotation will start with an 'r' or 'R', then followed by a double indicating revolutions -Any commands related to gripping will start with a 'g' or 'G', then followed by a 0 or 1. Other values will trigger an exception -Any commands related to extending the arm will start with an 'e' or 'E', then followed by a double indicating motor rotation. We will assert that the value is between -1 and 1 for now -Any unrecognized letter will return the ERROR enum and 1 as the value. Serial should display an error message, or trigger an exception Once the command is selected, the remaining value is parsed as a double, and then pointed to in the Arm_Command Pointer.
Parameters
rawinput The input from Serial or other communication method
Definition at line 49 of file Controller.cpp.
References Controller::arm_command::op, and Controller::arm_command::value.
printExec()
Controller::printExec ()
Debug Function to test the parser Prints output in the serial connection based on the values in currentCmd.
See also
Controller::parseSerial
Definition at line 81 of file Controller.cpp.
References getCommand(), and Controller::arm_command::op.
setCommand()
Controller::setCommand (Controller::Arm_Command * cmd)
Setter method for the currentCmd pointer.
Parameters
cmd The pointer to overwrite the current pointer of currentCmd
Definition at line 44 of file Controller.cpp.
The documentation for this class was generated from the following files:
Controller.h
Controller.cpp